### ISSUE TITLE
Can you add a license to the Raspberry PI midi Repo ?

### ISSUE THREAD

**Issue by Mylab6** [Hecsall/arduino-midi-footswitch#3]
Hi, 

I've been able to make fantastic progress building upon your amazing work. Could you add a license to it( MIT would be awesome !)

**Comment by Hecsall** [comment]
Hi Mylab6!
Thank you for taking the time to file this issue, I'm sorry for the (huge) delay, I didn't notice this issue before, I completely lost the notification.
As per your request, I added the MIT LICENSE file (I'm not really used to adding license files, my bad).

Hope your project is going well!
